export const FETCH_POKEMONS_START = "FETCH_POKEMONS_START";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";

export const FETCH_POKEMONS_ERROR = "FETCH_POKEMONS_ERROR";

export const FETCH_POKEMON_BY_ID_SUCCESS = "FETCH_POKEMON_BY_ID_SUCCESS";

export const SET_READY_TO_FETCH = "SET_READY_TO_FETCH";

export const ADD_COLLECTION_ITEM = "ADD_COLLECTION_ITEM";
export const ADD_POKEMON_STATUS = "ADD_POKEMON_STATUS";
