export const FETCH_POKEMON_GROUP_START = "FETCH_POKEMON_GROUP_START";
export const FETCH_POKEMON_GROUP_SUCCESS = "FETCH_POKEMON_GROUP_SUCCESS";
export const FETCH_POKEMON_GROUP_ERROR = "FETCH_POKEMON_GROUP_ERROR";
export const ADD_POKEMON_GROUP_SUCCESS = "ADD_POKEMON_GROUP_SUCCESS";

export const SET_READY_TO_FETCH = "SET_READY_TO_FETCH";

export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_ERROR = "FETCH_COLLECTION_ERROR";
export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";

export const FETCH_POKEMON_BY_ID_START = "FETCH_POKEMON_BY_ID_START";
export const FETCH_POKEMON_BY_ID_SUCCESS = "FETCH_POKEMON_BY_ID_SUCCESS";
export const FETCH_POKEMON_BY_ID_ERROR = "FETCH_POKEMON_BY_ID_ERROR";
