export const FETCH_POKEMON_GROUP_START = "FETCH_POKEMON_GROUP_START";
export const FETCH_POKEMON_GROUP_SUCCESS = "FETCH_POKEMON_GROUP_SUCCESS";
export const FETCH_POKEMON_GROUP_ERROR = "FETCH_POKEMON_GROUP_ERROR";
export const ADD_POKEMON_GROUP_SUCCESS = "ADD_POKEMON_GROUP_SUCCESS";

export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_ERROR = "FETCH_COLLECTION_ERROR";

export const FETCH_POKEMON_BY_ID_START = "FETCH_POKEMON_BY_ID_START";
export const FETCH_POKEMON_BY_ID_SUCCESS = "FETCH_POKEMON_BY_ID_SUCCESS";
export const FETCH_POKEMON_BY_ID_ERROR = "FETCH_POKEMON_BY_ID_ERROR";

export const RESET_COLLECTION = "RESET_COLLECTION";
export const RESET_POKEMON_GROUP = "RESET_POKEMON_GROUP";
